# Color Palette
COLOR_BURGUNDY = "#5D1535"
COLOR_DARK = "#1A1A1A"
COLOR_WHITE = "#FFFFFF"
COLOR_BG = "#F5F5F7"
COLOR_SURFACE = "#FFFFFF"
COLOR_DRAWER_BG = "#1A1A1A" # Dark/Black
COLOR_DRAWER_TEXT = "#FFFFFF" # White
COLOR_ACCENT = "#D4AF37" # Gold/Luxury Accent
